class ColorName
  MAROON = "maroon"
  RED = "red"
  ORANGE = "orange"
  YELLOW = "yellow"
  OLIVE = "olive"
  PURPLE = "purple"
  FUCHSIA = "fuchsia"
  WHITE = "white"
  LIME = "lime"
  GREEN = "green"
  NAVY = "navy"
  AQUA = "aqua"
  TEAL = "teal"
  BLACK = "black"
  SILVER = "silver"
  GRAY = "gray"
  BLUE = "blue"
end